### ISSUE TITLE
Make memorization of messages optional

### ISSUE THREAD

**Issue by scholz-timo** [jwalton/node-amqp-connection-manager#235] opened 2022-04-11 19:35 UTC
Hello, I am proposing a feature flag / option for the memorization of messages (When the connection is broken).

I want to rely on this library for my application and I would require such a functionality, since the in memory messages do not persist between restarts of the application and can cause some data loss.

**Comment by scholz-timo** [comment] 2022-04-15 14:43
Or add an option to memorize using different strategies (redis, filesystem, database, ...)

**Comment by Vslava** [comment] 2022-08-15 08:06
I need the same feature as @scholz-timo mentioned

**Comment by scholz-timo** [comment] 2022-11-28 11:41
@jwalton Are you intrested in such a feature for your library?

**Comment by scholz-timo** [comment] 2022-11-28 11:44
For me it would be enough to expose the ChannelWrapper, so i can patch my own logic into it.

**Comment by robross0606** [comment] 2024-03-12 15:13
Need same feature here.  Queueing offline to memory is not scalable or reliable.  We would need to be able to at least persist the offline queue to file system.  As mentioned by @scholz-timo , implementing an adapter pattern here would be great.

**Comment by jwalton** [comment] 2024-03-12 16:41
I'm going to close this issue.  I think this should probably be implemented in some other library rather than here.

The goal of this library is to provide a thin wrapper around [amqplib](https://amqp-node.github.io/amqplib/) which provides automatic reconnects.  We want the API of this library to be as close as possible to amqplib - ideally a drop in replacement (I think there's some breaking changes I could make to this library to make it even more of a drop in replacement, actually...) The only reason we buffer to memory is so that you don't have to care if you're connected or not when you try to send a message - you send a message, if you're not connected it will be sent when you reconnect. But, critically, we try to follow the API from amqplib: when you send a message, you get back a promise, and that promise resolves when the message is successfully sent.

It _seems_ like it ought to be easy, since we're storing messages in memory, to store them somewhere else instead.  It seems like we ought to be able to provide some kind on interface that a plugin could implement, and then storing in memory would be the default implementation of that plugin. The problem is that there's no way you can store an in-progress-promise in a database or on disk.  When your application restarts, and we reload queued messages from disk, and we send one of those messages, how would we notify the "caller" that the message has been sent?  The caller is long gone, since it died with the previous version of the application. There is not longer a deferred promise to resolve.

There's lots of ways we _could_ notify back to the application that the message was sent or was unsendable. We could assign these messages some kind of ID and emit an event with the ID and the ultimate status of the message.  But, this is no longer following the API from `amqplib`, and it adds a lot of complexity which many users may not need. I think ultimately it's outside the scope of what amqp-connection-manager is trying to do, and you'd be better off queueing your messages to disk, then calling into amqp-connection-manager, and removing messages from the queue when the promise resolves and tells you they've been sent.  Then you can handle loading messages from disk and wiring up the notification end of things when your application starts up. You could also build a wrapper around amqp-connection-manager which presents some other API.

With that as a given, the only reason to make the storage pluggable would be if you want to have a lot unsent messages queued up and you're afraid they won't all fit in memory.  I don't think that's what anyone is actually asking for, though.

**Closed** 2024-03-12 16:41 UTC

**Comment by robross0606** [comment] 2024-03-12 16:44
@jwalton, how do you notify callers if the request is cached to memory?  Do you currenlty just block on the promise indefinitely?

**Comment by jwalton** [comment] 2024-03-12 17:46
Exactly.  If you call `publish` for example, we [create a new Promise](https://github.com/jwalton/node-amqp-connection-manager/blob/599d31f01d2e13d6a049bd7645e39e5de99d0293/src/ChannelWrapper.ts#L299), and push the [resolve and reject](https://github.com/jwalton/node-amqp-connection-manager/blob/599d31f01d2e13d6a049bd7645e39e5de99d0293/src/ChannelWrapper.ts#L307-L308) onto the sent-messages queue.  When we get confirmation that the message has been sent (or has failed to send) we [call into resolve or reject](https://github.com/jwalton/node-amqp-connection-manager/blob/599d31f01d2e13d6a049bd7645e39e5de99d0293/src/ChannelWrapper.ts#L640-L644) to signal back to the caller.  If you specify a timeout, we'll [reject as soon as the timeout happens](https://github.com/jwalton/node-amqp-connection-manager/blob/master/src/ChannelWrapper.ts#L369-L370).
